---
version: "3.3"

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=test

  flyway:
    image: flyway/flyway
    command:
      - "-user=root"
      - "-password=P@ssw0rd"
      - "-url=jdbc:mysql://db:3306/test?allowPublicKeyRetrieval=true"
      - "-connectRetries=60"
      - "migrate"
    volumes:
      - ./database/migrations:/flyway/sql
    depends_on:
      - db

  app:
    image: local/kotlinapp
    ports:
      - 8080:8080
    depends_on:
      - db
      - flyway
