spring:
  datasource:
    url: jdbc:mysql://db:3306/test
    username: root
    password: P@ssw0rd

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        ddl-auto: create
